services:
  moneylagmysql:
    build:
      context: ../mysql
      dockerfile: Dockerfile
    image: moneylag-mysql:v1

  moneylag-backend:
    build:
      context: ../moneylag-backend
      dockerfile: Dockerfile
    image: moneylag-backend:v1

  moneylag-frontend:
    build:
      context: ../moneylag-frontend
      dockerfile: Dockerfile
    image: moneylag-frontend:v1