services:
  mysql:
    image: crud-mysql:v1
    container_name: crud-mysql
    environment:
      MYSQL_DATABASE: crud_app
      MYSQL_USER: crud
      MYSQL_PASSWORD: CrudApp@1
      MYSQL_ROOT_PASSWORD: siva
    ports:
      - "3306:3306"
    networks:
      - crud

  crud-redis:
    image: 384570460482.dkr.ecr.ap-south-1.amazonaws.com/redis:alpine3.22
    container_name: crud-redis
    networks:
      - crud

  crud-backend:
    image: crud-backend:v1
    container_name: crud-backend
    environment:
      DB_HOST: crud-mysql
      DB_NAME: crud_app
      DB_USER: crud
      DB_PASSWORD: CrudApp@1
      REDIS_HOST: crud-redis
      REDIS_SSL: "false"
      FEATURE_UPDATE: "true"
      FEATURE_DELETE_ALL: "true"
    depends_on:
      - mysql
      - crud-redis
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - crud

  # crud-frontend:
  #   image: crud-frontend:v1
  #   container_name: crud-frontend
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ../nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - crud-backend
  #   restart: unless-stopped
  #   networks:
  #     - crud
networks:
  crud:
    driver: bridge