services:
  moneylag-mysql:
    image: moneylag-mysql:v1
    container_name: moneylag-mysql
    environment:
      MYSQL_DATABASE: moneylag_app
      MYSQL_USER: moneylag
      MYSQL_PASSWORD: moneylagApp@1
      MYSQL_ROOT_PASSWORD: siva
    # ports:
    #   - "3306:3306"
    restart: unless-stopped
    networks:
      - moneylag

  moneylag-redis:
    image: 384570460482.dkr.ecr.ap-south-1.amazonaws.com/redis:alpine3.22
    container_name: moneylag-redis
    # ports:
    #   - "6379:6379"
    restart: unless-stopped
    networks:
      - moneylag

  moneylag-backend:
    image: moneylag-backend:v1
    container_name: moneylag-backend
    environment:
      DB_HOST: moneylag-mysql
      DB_NAME: moneylag_app
      DB_USER: moneylag
      DB_PASSWORD: moneylagApp@1
      REDIS_HOST: moneylag-redis
      REDIS_SSL: "false"
      FEATURE_UPDATE: "true"
      FEATURE_DELETE_ALL: "true"
    depends_on:
      - moneylag-mysql
      - moneylag-redis
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - moneylag
  moneylag-frontend:
    image: moneylag-frontend:v1
    container_name: moneylag-frontend
    environment:
      BACKEND_SERVICE: moneylag-backend
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../env.js:/usr/share/nginx/html/env.js:ro
    depends_on:
      - moneylag-backend
    restart: unless-stopped
    networks:
      - moneylag
networks:
  moneylag:
    driver: bridge