---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_DATABASE: moneylag_app
  MYSQL_USER: moneylag
  MYSQL_PASSWORD: moneylagApp@1
  MYSQL_ROOT_PASSWORD: siva
---
apiVersion: v1
kind: Service
metadata:
  name: moneylag-mysql
  labels:
    app: moneylag-mysql
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app: moneylag-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moneylag-mysql
spec:
  serviceName: moneylag-mysql
  replicas: 1
  selector:
    matchLabels:
      app: moneylag-mysql
  template:
    metadata:
      labels:
        app: moneylag-mysql
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mysql
          image: moneylag-mysql:v1
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - secretRef:
                name: mysql-secret
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -uroot -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -uroot -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
       storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
