CREATE DATABASE IF NOT EXISTS crud_app;
USE crud_app;

CREATE TABLE entries (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  amount DOUBLE NOT NULL,
  description VARCHAR(255) NOT NULL,
  date DATE NOT NULL  
);

CREATE USER IF NOT EXISTS 'crud'@'%' IDENTIFIED BY 'CrudApp@1';
GRANT ALL ON crud_app.* TO 'crud'@'%';
FLUSH PRIVILEGES;